clc;
clear all;
ngrafo = input('Archivo de grafo = ', 's');
%ngrafo = strcat(ngrafo,'.txt'); 
%fm = input('Flujo máximo = ');
ngrafo = strcat(ngrafo,'temp.ffm');
dest = dlmread(ngrafo,' ', [0 0 0 13]);
dest = dest + 1;
cod = dlmread(ngrafo,' ', [1 0 1 3]);
cod = cod + 1;
C = dlmread(ngrafo,' ',2,0);
%nn = length(C);
%fprintf('Nodos destinos\n');
%disp(dest);
%leerGrafo=C;
%[C, dest]=ff_leerGrafo();
h=view(biograph(C,[],'ShowWeights','on'));
set(h.Nodes(dest),'Color',[1 0 1]);
set(h.Nodes(cod(1,:)),'Color',[0 1 0]);
